[path]
	InputConcentration = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\concentration"
	InputDischarge = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\discharge"
	InputSiteInfo = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\SiteInfo.csv"
	OutputPath =  "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\OUTPUT"
	OutputPlot = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\OUTPUT\\Plot"

[param]
	Percentile = [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95] # Percentile of output file
	"ğŸ_FilterData" = true # <false> || <true>. If <true> than Q and P will be filtered as below.
		QminTreshold = 0.04 #  [m Â³ s â»Â³] minimum value of Q which are removed for analysis
		PminTreshold = 0.0001 # [g mâ»Â³] minimum value of phosphorous data which are removed from analysis

	NoValue = -9999 # need to be negative. The value is not imporant as the sites witth NoVlue are removed
	MinDataPointPerSite = 365 # Minimum number of observation of sites required to make observation. If the creteria is ot meet than the site is removed

[baseflow]
   "Î”TtimeLag_Min"  = 4 # [day] windows period were the search for minimum flow is computed
	Perc_IncreaseDecrease = 0.01 # [0-1] assure that between local minima there is a steady increase of decrease and not flat
   "ğŸ_LocalMinima" = true # <true> Use method of finding local minima
   "ğŸ_Reduce"      = false # <true> Search during period were flow is decreasing
	"ğŸ_Qvariability" = true # <true> accounting for the variability of the flow: Q_Std / (Q_Max-Q_Min)
	"ğŸ_LocalMinimaClean" = true # <true> then the local minima needs to be well formed

[plot]
	"ğŸ_Plot_EverySite" = true
	"ğŸ_Plot_AllSites" = true
	"ğŸ_PlotLog1p" = false # Plot by using log transforemation