[path]
	InputConcentration = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\concentration"
	InputDischarge = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\discharge"
	InputSiteInfo = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\SiteInfo.csv"
	OutputPath =  "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\OUTPUT"
	OutputPlot = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\OUTPUT\\Plot"

[param]
	Percentile = [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
	QminTreshold = 0.04 # minimum value of Q [m3 s-1]
	PminTreshold = 0.01
	"üéè_FilterData" = true # <false> || <true>. If true than Q < QminTreshold will be removed.
	NoValue = -9999
	MinDataPointPerSite = 365

[baseflow]
   "ŒîTtimeLag_Min"  = 4 # 3-5
   "ŒîTtimeLag_Max"  = 4
   "üéè_LocalMinima" = true
   "üéè_Reduce"      = false
	Perc_IncreaseDecrease = 0.05

[plot]
	"üéè_Plot_EverySite" = true
	"üéè_Plot_AllSites" = true
	"üéè_PlotLog1p" = true