[path]
	InputConcentration = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\concentration"
	InputDischarge = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\INPUT\\discharge"
	OutputPath =  "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\OUTPUT"
	OutputPlot = "D:\\JOE\\MAIN\\MODELS\\PHOSPHOROUS\\PhosporousTransferIndices\\DATA\\OUTPUT\\Plot"

[param]
	Percentile = [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]

